{
 "title": "DORA",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Lead Time for Changes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n    d.deploy_id,\n    DATE(d.time_created) AS day,\n    -- ignore automated pushes.\n    AVG(IF(TIMESTAMPDIFF(SECOND, c.time_created, d.time_created) > 0, TIMESTAMPDIFF(SECOND, c.time_created, d.time_created), 0)) as avg_time_to_change\n  FROM deployments d\n  LEFT JOIN changes c ON d.change_id = c.change_id\nGROUP BY day ORDER BY day"
    }
   ]
  },
  {
   "title": "Lead Time to Change Bucket",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CASE\n    WHEN d.avg_time_to_change < 24 * 60 then \"One day\"\n    WHEN d.avg_time_to_change < 168 * 60 then \"One week\"\n    WHEN d.avg_time_to_change < 730 * 60 then \"One month\"\n    WHEN d.avg_time_to_change < 730 * 6 * 60 then \"Six months\"\n    ELSE \"One year\"\n  END as lead_time_to_change,\n  d.avg_time_to_change\nFROM\n  (\n    SELECT\n  d.deploy_id,\n  DATE(d.time_created) AS day,\n  -- ignore automated pushes.\n  AVG(\n    IF(\n      TIMESTAMPDIFF(MINUTE, c.time_created, d.time_created) > 0,\n      TIMESTAMPDIFF(MINUTE, c.time_created, d.time_created),\n      NULL\n    )\n  ) as avg_time_to_change\nFROM\n  deployments d\n  LEFT JOIN changes c ON d.change_id = c.change_id\n        WHERE\n          d.time_created > TIMESTAMP($__timeFrom())\n  ) d"
    }
   ]
  },
  {
   "title": "Daily Deployments",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\ndate(time_created) as date_created,\nCOUNT(distinct deploy_id) AS deployments\nFROM\ndeployments\nGROUP BY date_created"
    }
   ]
  },
  {
   "title": "Deployment Frequency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\ndate(time_created) as date_created,\nCOUNT(distinct deploy_id)/FLOOR(DATEDIFF(CURRENT_DATE(), $__timeFrom())/7) AS avg_deploys_per_week\nFROM\ndeployments"
    }
   ]
  },
  {
   "title": "Daily Average Time to Restore Services",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE(time_created) as day,\n  AVG(TIMESTAMPDIFF(MINUTE, time_created, time_resolved)) as daily_med_time_to_restore\nFROM\n  incidents\nGROUP BY day"
    }
   ]
  },
  {
   "title": "Average Time to Restore Services",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CASE\n    WHEN i.daily_med_time_to_restore < 24 then \"One day\"\n    WHEN i.daily_med_time_to_restore < 168 then \"One week\"\n    WHEN i.daily_med_time_to_restore < 730 then \"One month\"\n    WHEN i.daily_med_time_to_restore < 730 * 6 then \"Six months\"\n    ELSE \"One year\"\n  END as med_time_to_resolve,\n  i.daily_med_time_to_restore\nFROM\n  (\nSELECT\n  DATE(time_created) as day,\n  AVG(TIMESTAMPDIFF(HOUR, time_created, time_resolved)) as daily_med_time_to_restore\nFROM\n  incidents\nWHERE\n  time_resolved > $__timeFrom()) i"
    }
   ]
  },
  {
   "title": "Daily Change Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\nDATE(d.time_created) as day,\nSUM(IF(i.incident_id is NULL, 0, 1)) / COUNT(DISTINCT deploy_id) as change_fail_rate\nFROM deployments d\nLEFT JOIN (SELECT\n        incident_id,\n        changes\n        FROM incidents i) i ON i.changes = d.change_id\ngroup by day;"
    }
   ]
  },
  {
   "title": "Change Failure Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CASE\n    WHEN s.change_fail_rate <=.15 then \"0-15%\"\n    WHEN s.change_fail_rate <.46 then \"16-45%\"\n    ELSE \"46-60%\"\n  end as change_fail_rate,\n  s.change_fail_rate as rate\nFROM\n(SELECT\n  DATE(d.time_created) as day,\n  SUM(IF(i.incident_id is NULL, 0, 1)) / COUNT(DISTINCT deploy_id) as change_fail_rate\nFROM\n  deployments d\n  LEFT JOIN (\n    SELECT\n      incident_id,\n      changes\n    FROM\n      incidents i\n  ) i ON i.changes = d.change_id\n  WHERE\n  d.time_created > $__timeFrom()\n) s\n  LIMIT 1;"
    }
   ]
  }
 ]
}