apiVersion: apps/v1
kind: Deployment
metadata:
  name: dora-event-handler
  namespace: dora
spec:
  selector:
    matchLabels:
      app: dora-event-handler
  template:
    metadata:
      labels:
        app: dora-event-handler
    spec:
      serviceAccountName: dora-event-handler
      containers:
      - name: dora-event-handler
        image: 492946569230.dkr.ecr.eu-central-1.amazonaws.com/dora-event-handler:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
          - name: AUTH_SECRET
            valueFrom:
              secretKeyRef:
                name: dora-webhook-secrets
                key: github-webhook-secret
          - name: PROJECT_NAME
            valueFrom:
              configMapKeyRef:
                name: dora-config
                key: project_name
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dora-event-handler
  namespace: dora
spec:
  selector:
    app: dora-event-handler
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: dora-webhook-secrets
  namespace: dora
type: Opaque
data:
  github-webhook-secret: YW5hYXJlbWVyZQ==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dora-config
  namespace: dora
data:
  project_name: TEST-DORA
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":
      { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:492946569230:certificate/6bbb3067-1567-455b-8d6d-4de9b4e55fad
    alb.ingress.kubernetes.io/group.name: eks-operations-1-a
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: routing.http.drop_invalid_header_fields.enabled=true
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=operations, Provider=Managed by aws-load-balancer-controller
    external-dns.alpha.kubernetes.io/hostname: dora.aws.vivino.com
    kubernetes.io/ingress.class: alb
  name: dora-event-handler
  namespace: dora
spec:
  rules:
  - host: dora.vivino.com
    http:
      paths:
      - backend:
          service:
            name: dora-event-handler
            port:
              number: 80
        path: /event-handler
        pathType: Prefix
  tls:
  - hosts:
    - dora.vivino.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::492946569230:role/eks-operations-1-dora-event-handler
  name: dora-event-handler
  namespace: dora